# POST http://127.0.0.1:5000/verify_user HTTP/1.1
# content-type: application/json

# {
#     "username":"Sanjo",
#     "pwd":"helloworld"
# }



# GET http://127.0.0.1:5000/get_users HTTP/1.1
# content-type: application/json


# POST https://scrumbledore-server.herokuapp.com/verify_user HTTP/1.1
# content-type: application/json

# {
#     "username":"Sanjo",
#     "pwd":"helloworld"
# }



# POST https://scrumbledore-server.herokuapp.com/add_user HTTP/1.1
# content-type: application/json

# {
#     "username":"Amrit",
#     "pwd":"helloworld2"
# }

# GET http://127.0.0.1:5000/get_allprojects HTTP/1.1
# content-type: application/json


# POST http://127.0.0.1:5000/add_project HTTP/1.1
# content-type: application/json

# {
#     "projectid":"Project4",
#     "projectdesc":"helloworld",
#     "users":["Sanjo", "Amrit"]
# }

# POST http://127.0.0.1:5000/get_project HTTP/1.1
# content-type: application/json

# {
#     "projectid":"Project1"
# }

# POST https://scrumbledore-server.herokuapp.com/add_project HTTP/1.1
# content-type: application/json

# {
#     "projectid":"Project5",
#     "projectdesc":"Project Desc5",
#     "users":["Sanjo", "Amrit"]
# }

# POST https://scrumbledore-server.herokuapp.com/get_project HTTP/1.1
# content-type: application/json

# {
#     "projectid":"Project1"
# }


# GET http://127.0.0.1:5000/get_hardwareset HTTP/1.1
# content-type: application/json


# GET https://scrumbledore-server.herokuapp.com/get_hardwareset HTTP/1.1
# content-type: application/json

# # POST https://react-flask-sanjo.herokuapp.com/get_surname HTTP/1.1
# # content-type: application/json

# # {
# #     name: "Sanjo"
# # }

# POST https://scrumbledore-server.herokuapp.com/resource_management HTTP/1.1
# content-type: application/json

# {
#     "projectid":"Project1",
#     "operation":"check-in",
#     "requestvalue":[
#         {
#             "resourceid":"HW1",
#             "value":4
#         },
#         {
#             "resourceid":"HW2",
#             "value":10
#         }
#     ]
# }

# POST https://scrumbledore-server.herokuapp.com/resource_management HTTP/1.1
# content-type: application/json

# {
#     "projectid":"Project7",
#     "operation":"check-out",
#     "requestvalue"[
#         {"HW1": 50},
#         {"HW2":0}
#     ]
# }

POST https://scrumbledore-server.herokuapp.com/resource_management HTTP/1.1
content-type: application/json

{
    "projectid":"Project1",
    "operation":"check-in",
    "requestvalue":[
        {
            "resourceid":"HW1",
            "value":4
        },
        {
            "resourceid":"HW2",
            "value":0
        }
    ]
}

# POST https://scrumbledore-server.herokuapp.com/resource_management HTTP/1.1
# content-type: application/json

# {
#     "projectid":"Project7",
#     "operation":"check-out",
#     "requestvalue"[
#         {"HW1": 50},
#         {"HW2":0}
#     ]
# }

# POST http://127.0.0.1:5000/get_specificProject HTTP/1.1
# content-type: application/json

# {
#     "projectid":"Project1"
# }